[
    {
        "WfName": "WorkshopProposal",
        "AcessPermission": "Private", 
        "AuthGroups": ["Berger Portal Owners"],
        "AuthUsersADId": [208, 296, 350, 21],
        "AuthUsersEmpId": [1270, 334],  
        "DisplayTxt": "Workshop Proposal Dashboard",
        "ViewUrl": { "siteUrl": "leaveauto/SitePages/WorkshopProposal.aspx?UniqueId=", "qryStrKeyTyp": "GUID", "mode": "&mode=read", "titleTag": "WP-" },
        "MasterListInfo": { "name": "WorkshopProposalMaster", "select": "GUID,ID,Title,WorkshopPurposeOrObjective,ActualExpenditure,PendingWith/ID,PendingWith/Title,Author/ID,Created,Status,Author/Title,Author/Office,Author/JobTitle,TotalEstimatedAmount,EmployeeID&$expand=PendingWith/ID,Author/ID&$orderby=Created desc", "primaryKey": "Title"},
        "RenderDetListInfo": [{ "name": "WorkshopProposalInfo", "select": "ID,Title,WorkshopPurposeOrObjective,ActualExpenditure,PendingWith/ID,PendingWith/Title,Author/ID,Created,Status,Author/Title,TotalEstimatedAmount&$expand=PendingWith/ID,Author/ID"}],
        "DetailsListInfo": [{ "name": "WorkshopProposalInfo", "select": "ID,Title,ExpectedDate, Author/ID, Author/Office, WorkshopLocation, ExpectedParticipant, Purpose, TotalAmount, Title, GLCode, CostCenter, IONumber, FoodCost, HallOrVenueRent, PromotionalItem, DecorationCost, OtherCost, BudgetedExpenditure, ActualLocation, ActualParticipant, ActualFoodCost, ActualDecorationCost, ActualHallOrVenueRent, ActualPromotionalItem, ActualExpenditure, ActualOtherCost&$expand=Author/ID&$orderby=Created desc", "primaryKey": "Title"}],
        "DbViewColDef": [
            { "fldType": "ViewLinkGuidField", "headerName": "View", "field": "GUID", "editable":false, "minWidth": 80 },
            { "fldType": "TitleWitouthMDField", "headerName": "RequestID", "field": "Title", "editable":false, "minWidth": 120 },
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "editable":false, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "EstimatedAmount", "field": "TotalEstimatedAmount", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "editable":false, "minWidth": 140 },
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "editable":true, "minWidth": 165 },                
            { "fldType": "TextField", "headerName": "Emp. Id", "field": "EmployeeID", "editable":true, "minWidth": 120, "hide":true },
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "editable":false, "minWidth": 165 }
        ],
        "MasterDetailViewColDef": [
            { "fldType": "ViewLinkGuidField", "headerName": "View", "field": "GUID", "editable":false, "minWidth": 80 },            
            { "fldType": "TitleWitouthMDField", "headerName": "RequestID", "field": "Title", "editable":false, "minWidth": 120 },
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "editable":false, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "EstimatedAmount", "field": "TotalEstimatedAmount", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "editable":false, "minWidth": 140 },
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "editable":true, "minWidth": 165 },                
            { "fldType": "TextField", "headerName": "Emp. Id", "field": "EmployeeID", "editable":true, "minWidth": 120, "hide":true },
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "editable":false, "minWidth": 165 },           
            { "fldType": "GetSetDateField", "headerName": "Date", "field": "ExpectedDate", "valueGetter":"ExpectedDate", "editable":false, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "Location", "field": "WorkshopLocation", "editable":false, "minWidth": 220 },
            { "fldType": "TextField", "headerName": "PromotionalItem", "field": "PromotionalItem", "editable":false, "minWidth": 165 },
            { "fldType": "NumberField", "headerName": "Ex.Participant", "field": "ExpectedParticipant", "editable":false, "minWidth": 160 },
            { "fldType": "NumberField", "headerName": "Ac.Participant", "field": "ActualParticipant", "editable":false, "minWidth": 160 }                        
        ]
    },
    {
        "WfName": "PoolCarRequisition",
        "AcessPermission": "Public",
        "AuthGroups": ["Berger Portal Owners"],
        "AuthUsersADId": "[208, 296, 350, 21, 1026]",
        "AuthUsersEmpId": "['334', '1270']",  
        "DisplayTxt": "PoolCar Requisition Dashboard",
        "ViewUrl": { "siteUrl": "leaveauto/SitePages/PoolCarRequisition.aspx?UniqueId=", "qryStrKeyTyp": "GUID", "mode": "&mode=read" },
        "MasterListInfo": { "name": "PoolCarRequisitionInfo", "select": "GUID,OficeOfReservationFor,ID,Title,EmployeeId,EmployeeName,StartDate,EndDate,NoOfDays,StartTime,EndTime,TotalHours,AccompaniedPersonNo,AccompaniedPersonsName,PlaceOfVisit,PurposeOfVisit,Status,PendingWith/ID,PendingWith/Title,Created,AssignedCarNo,AssignedDriver,DriverMobileNo,Author/ID, Author/Title, Author/Office, Author/JobTitle&$expand=PendingWith/ID,Author/ID&$orderby=Created desc", "primaryKey": "Title"},
        "RenderDetListInfo": [{ "name": "PoolCarRequisitionInfo", "select": "GUID,OficeOfReservationFor,ID,Title,EmployeeId,EmployeeName,StartDate,EndDate,NoOfDays,StartTime,EndTime,TotalHours,AccompaniedPersonNo,AccompaniedPersonsName,PlaceOfVisit,PurposeOfVisit,Status,PendingWith/ID,PendingWith/Title,Created,AssignedCarNo,AssignedDriver,DriverMobileNo,Author/ID, Author/Title, Author/Office, Author/JobTitle&$expand=PendingWith/ID,Author/ID&$orderby=Created desc"}],
        "DetailsListInfo": [{ "name": "PoolCarRequisitionInfo", "select": "GUID,OficeOfReservationFor,ID,Title,EmployeeId,EmployeeName,StartDate,EndDate,NoOfDays,StartTime,EndTime,TotalHours,AccompaniedPersonNo,AccompaniedPersonsName,PlaceOfVisit,PurposeOfVisit,Status,PendingWith/ID,PendingWith/Title,Created,AssignedCarNo,AssignedDriver,DriverMobileNo,Author/ID, Author/Title, Author/Office, Author/JobTitle&$expand=PendingWith/ID,Author/ID&$orderby=Created desc", "primaryKey": "Title"}],
        "DbViewColDef": [
            { "fldType": "ViewLinkGuidField", "headerName": "View", "field": "GUID", "minWidth": 165},
            { "fldType": "TitleWitouthMDField", "headerName": "RequestID", "field": "Title", "minWidth": 120},
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "minWidth": 120},
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "minWidth": 165},            
            { "fldType": "TextField", "headerName": "Visit Start Time", "field": "StartDate", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Place Of Visit", "field": "PlaceOfVisit", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Location", "field": "Author.Office", "minWidth": 165, "hide":true},
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "minWidth": 165}
        ],
        "MasterDetailViewColDef": [
            { "fldType": "ViewLinkGuidField", "headerName": "View", "field": "GUID", "minWidth": 165},
            { "fldType": "TitleWitouthMDField", "headerName": "RequestID", "field": "Title", "minWidth": 120},
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "minWidth": 120},
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "minWidth": 165},            
            { "fldType": "TextField", "headerName": "Visit Start Time", "field": "StartDate", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Place Of Visit", "field": "PlaceOfVisit", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Location", "field": "Author.Office", "minWidth": 165, "hide":true},
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "minWidth": 165}
        ]

    },
    {
        "WfName": "EmployeePaintDiscount",
        "AcessPermission": "Public",
        "AuthGroups": ["Berger Portal Owners"],
        "AuthUsersADId": [21, 1026, 194, 47, 450, 447],
        "AuthUsersEmpId": [232, 334, 1270],  
        "DisplayTxt": "Employee Paint Discount Dashboard",
        "ViewUrl": { "siteUrl": "leaveauto/SitePages/EmployeePaintDiscount.aspx?UniqueId=", "qryStrKeyTyp": "GUID", "mode": "&mode=read" },
        "MasterListInfo": { "name": "EmpPaintDiscountRequest", "select": "Title, ID, GUID, Modified, Created, PendingWith/ID, PendingWith/Title, Author/ID, Author/Title, Author/Office, Author/JobTitle, Status, DeliveryOffice, DelOfcInvIncharge/ID, DelOfcInvIncharge/Title,RequestInfo&$expand=PendingWith/ID,Author/ID,DelOfcInvIncharge/ID&$orderby=Created desc", "primaryKey": "Title"},
        "RenderDetListInfo": [{ "name": "EmpPaintDiscountRequest", "select": "Title, ID, GUID , Modified , Created , PendingWith/ID , PendingWith/Title , Author/ID , Author/Title , Author/Office , Author/JobTitle , Status, DeliveryOffice, DelOfcInvIncharge/ID, DelOfcInvIncharge/Title,RequestInfo&$expand=PendingWith/ID,Author/ID&$orderby=Created desc"}],
        "DetailsListInfo": [{ "name": "EmpPaintDiscountRequest", "select": "Title, ID, GUID , Modified , Created , PendingWith/ID , PendingWith/Title , Author/ID , Author/Title , Author/Office , Author/JobTitle , Status, DeliveryOffice, DelOfcInvIncharge/ID, DelOfcInvIncharge/Title,RequestInfo&$expand=PendingWith/ID,Author/ID&$orderby=Created desc", "primaryKey": "Title"}],
        "DbViewColDef": [
            { "fldType": "ViewLinkGuidField", "headerName": "View", "field": "GUID", "minWidth": 165},
            { "fldType": "TitleWitouthMDField", "headerName": "RequestID", "field": "Title", "minWidth": 120},
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "minWidth": 120},
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "minWidth": 165},            
            { "fldType": "TextField", "headerName": "DeliveryOffice", "field": "DeliveryOffice", "minWidth": 165, "valueGetter": "(JSON.parse(data.RequestInfo)).DeliveryOffice"},
            { "fldType": "TextField", "headerName": "Del.Off.Inv.Incharge", "field": "DelOfcInvIncharge.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Location", "field": "Author.Office", "minWidth": 165, "hide":true},
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "minWidth": 165}
        ],
        "MasterDetailViewColDef": [
            { "fldType": "ViewLinkGuidField", "headerName": "View", "field": "GUID", "minWidth": 165},
            { "fldType": "TitleWitouthMDField", "headerName": "RequestID", "field": "Title", "minWidth": 120},
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "minWidth": 120},
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "minWidth": 165},            
            { "fldType": "TextField", "headerName": "DeliveryOffice", "field": "DeliveryOffice", "minWidth": 165, "valueGetter": "(JSON.parse(data.RequestInfo)).DeliveryOffice"},
            { "fldType": "TextField", "headerName": "Del.Off.Inv.Incharge", "field": "DelOfcInvIncharge.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Location", "field": "Author.Office", "minWidth": 165, "hide":true},
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "minWidth": 165}
        ]
    },
    {
        "WfName": "CareCardSubmissionProcess",
        "AcessPermission": "Public",
        "AuthGroups": ["Berger Portal Owners"],
        "AuthUsersADId": [208, 296, 350, 21, 1026],
        "AuthUsersEmpId": [334, 1270],  
        "DisplayTxt": "Care Card Submission",
        "ViewUrl": { "siteUrl": "leaveauto/SitePages/CareCardSubmissionProcess.aspx?UniqueId=", "qryStrKeyTyp": "GUID", "mode": "&mode=read" },
        "MasterListInfo": { "name": "CareCardSubmissionProcessInfo", "select": "GUID,UniqueId,ID,RequestId,EmployeeId,EmployeeName,ObservationDate,ObservationTime,Site,OtherSite,SpecificArea,ObservationCategory,ObservationCategory01,ObservationCategory02,CaringObservation,ImmediateAction,SuggestionProposed,CommunicatedWith,CardSubmitted,WorkingAtHeight,PressureEnergy,FireExplosion,HeatThermalEnergy,ConfinedSpace,Lighting,EmergencyResponse,Noise,EmergencyExit,ManualHandling,EmergencyEquipment,Ventilation,VehicleManagement,MaterialStored,ChemicalTransfer,EnvironmentalEmission,ChemicalStorage,HealthIssue,ChemicalSpillage,UseOfNormalPPE,HouseKeeping,UseOfSpecializedPPE,MachineEquipment,PersonalBehavior,LiftingOperation,HandTools,StoredEnergy,ToolsEquipment,ElectricalEnergy,RiskAssessment,Excavation,PendingWith/ID,PendingWith/Title,Created,Status,Author/ID, Author/Title, Author/Office, Author/JobTitle&$expand=PendingWith/ID,Author/ID&$orderby=Created desc", "expand": "Author , PendingWith", "orderByPrm": "Created", "orderByVal": false, "top": 100000, "primaryKey": "Title"},
        "DetailsListInfo": { "name": "CareCardSubmissionProcessInfo", "select": "GUID,UniqueId,ID,RequestId,EmployeeId,EmployeeName,ObservationDate,ObservationTime,Site,OtherSite,SpecificArea,ObservationCategory,ObservationCategory01,ObservationCategory02,CaringObservation,ImmediateAction,SuggestionProposed,CommunicatedWith,CardSubmitted,WorkingAtHeight,PressureEnergy,FireExplosion,HeatThermalEnergy,ConfinedSpace,Lighting,EmergencyResponse,Noise,EmergencyExit,ManualHandling,EmergencyEquipment,Ventilation,VehicleManagement,MaterialStored,ChemicalTransfer,EnvironmentalEmission,ChemicalStorage,HealthIssue,ChemicalSpillage,UseOfNormalPPE,HouseKeeping,UseOfSpecializedPPE,MachineEquipment,PersonalBehavior,LiftingOperation,HandTools,StoredEnergy,ToolsEquipment,ElectricalEnergy,RiskAssessment,Excavation,PendingWith/ID,PendingWith/Title,Created,Status,Author/ID, Author/Title, Author/Office, Author/JobTitle&$expand=PendingWith/ID,Author/ID&$orderby=Created desc", "expand": "Author , PendingWith", "orderByPrm": "Created", "orderByVal": false, "top": 100000, "primaryKey": "Title"},
        "DbViewColDef": [
            { "fldType": "ViewLinkGuidField", "headerName": "View", "field": "GUID", "minWidth": 165},
            { "fldType": "TitleWitouthMDField", "headerName": "RequestId", "field": "RequestId", "minWidth": 120},
            { "fldType": "DaGetSetDateFieldteField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "minWidth": 120},
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Emp.ID", "field": "EmployeeId", "minWidth": 120},
            { "fldType": "GetSetDateField", "headerName": "ObservationDate", "field": "ObservationDate", "valueGetter":"ObservationDate", "minWidth": 160},            
            { "fldType": "TextField", "headerName": "Site", "field": "Site", "minWidth": 165},
            { "fldType": "TextField", "headerName": "SpecificArea", "field": "SpecificArea", "minWidth": 165},
            { "fldType": "TextField", "headerName": "ObservationCategory", "field": "ObservationCategory", "minWidth": 205},
            { "fldType": "TextField", "headerName": "Communicated", "field": "CommunicatedWith", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "CardSubmitted", "field": "CardSubmitted", "minWidth": 180},
            { "fldType": "TextField", "headerName": "Location", "field": "Author.Office", "minWidth": 165, "hide":true},
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "minWidth": 165}
        ],
        "MasterDetailViewColDef": [
            { "fldType": "ViewLinkGuidField", "headerName": "View", "field": "GUID", "minWidth": 165},
            { "fldType": "TitleWitouthMDField", "headerName": "RequestId", "field": "RequestId", "minWidth": 120},
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "minWidth": 120},
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Emp.ID", "field": "EmployeeId", "minWidth": 120},
            { "fldType": "GetSetDateField", "headerName": "ObservationDate", "field": "ObservationDate", "valueGetter":"ObservationDate", "minWidth": 160},            
            { "fldType": "TextField", "headerName": "Site", "field": "Site", "minWidth": 165},
            { "fldType": "TextField", "headerName": "SpecificArea", "field": "SpecificArea", "minWidth": 165},
            { "fldType": "TextField", "headerName": "ObservationCategory", "field": "ObservationCategory", "minWidth": 205},
            { "fldType": "TextField", "headerName": "Communicated", "field": "CommunicatedWith", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "CardSubmitted", "field": "CardSubmitted", "minWidth": 180},
            { "fldType": "TextField", "headerName": "Location", "field": "Author.Office", "minWidth": 165, "hide":true},
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "minWidth": 165}
        ]
    },
    {
        "WfName": "creditDiscountApproval",
        "AcessPermission": "Protected",
        "AuthGroups": ["Berger Portal Owners"],
        "AuthUsersADId": [208, 296, 350, 21, 1026],
        "AuthUsersEmpId": [334, 1270],  
        "DisplayTxt": "Credit Discount Report",
        "ViewUrl": { "siteUrl": "leaveauto/SitePages/creditDiscountApproval.aspx?creditID=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CRDIS ID-" },
        "MasterListInfo": { "name": "CreditDiscountApprovalMain", "select": "GUID,ID,Title,EmployeeID,EmployeeName,ApplicationFor,CustomerID,CustomerType,Division,Channel,CreditDays,CreditAmount,BuyerType,NoOfExtProject,NoOfCompletedProject,PendingWith/ID,PendingWith/Title,Created,Status,Author/ID, Author/Title, Author/Office, Author/JobTitle&$expand=PendingWith/ID,Author/ID&$orderby=Created desc", "expand": "Author , PendingWith", "orderByPrm": "Created", "orderByVal": false, "top": 100000, "primaryKey": "ID"},
        "RenderDetListInfo": [{ "name": "CreditDiscountApprovalMain", "select": "GUID,ID,Title,EmployeeID,EmployeeName,ApplicationFor,CustomerID,CustomerType,Division,Channel,CreditDays,CreditAmount,BuyerType,NoOfExtProject,NoOfCompletedProject,PendingWith/ID,PendingWith/Title,Created,Status,Author/ID, Author/Title, Author/Office, Author/JobTitle&$expand=PendingWith/ID,Author/ID&$filter=Title ne null&$orderby=Created desc", "primaryKey": "ID"}],
        "DetailsListInfo": [{ "name": "CreditDiscountApprovalMain", "select": "GUID,ID,Title,EmployeeID,EmployeeName,ApplicationFor,CustomerID,CustomerType,Division,Channel,CreditDays,CreditAmount,BuyerType,NoOfExtProject,NoOfCompletedProject,PendingWith/ID,PendingWith/Title,Created,Status,Author/ID, Author/Title, Author/Office, Author/JobTitle&$expand=PendingWith/ID,Author/ID&$filter=Title ne null&$orderby=Created desc", "primaryKey": "ID"}],
        "DbViewColDef": [
            { "fldType": "ViewLinkIdField", "headerName": "RequestId", "field": "Title", "minWidth": 120, "siteUrl": "leaveauto/SitePages/creditDiscountApproval.aspx?creditID=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CRDIS ID-" },
            { "fldType": "TitleWitouthMDField", "headerName": "RequestId", "field": "Title", "minWidth": 120 },
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "minWidth": 120},
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Emp.ID", "field": "EmployeeID", "minWidth": 120},
			{ "fldType": "TextField", "headerName": "ApplicationFor", "field": "ApplicationFor", "minWidth": 220},
			{ "fldType": "TextField", "headerName": "Status", "field": "Status", "minWidth": 165},            
            { "fldType": "TextField", "headerName": "CustomerID", "field": "CustomerID", "minWidth": 165},
			{ "fldType": "TextField", "headerName": "CustomerType", "field": "CustomerType", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Division", "field": "Division", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Channel", "field": "Channel", "minWidth": 205},
			{ "fldType": "TextField", "headerName": "CreditDays", "field": "CreditDays", "minWidth": 205},
            { "fldType": "TextField", "headerName": "CreditAmount", "field": "CreditAmount", "minWidth": 165},
			{ "fldType": "TextField", "headerName": "BuyerType", "field": "BuyerType", "minWidth": 165},
			{ "fldType": "TextField", "headerName": "NoOfExtProject", "field": "NoOfExtProject", "minWidth": 165},
			{ "fldType": "TextField", "headerName": "NoOfCompletedProject", "field": "NoOfCompletedProject", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Location", "field": "Author.Office", "minWidth": 165, "hide":true},
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "minWidth": 165}            
        ],
        "MasterDetailViewColDef": [
            { "fldType": "ViewLinkIdField", "headerName": "RequestId", "field": "Title", "minWidth": 120, "siteUrl": "leaveauto/SitePages/creditDiscountApproval.aspx?creditID=", "qryStrKeyTyp": "ID", "mode": "&mode=read", "titleTag": "CRDIS ID-"},
            { "fldType": "TitleWitouthMDField", "headerName": "RequestId", "field": "Title", "minWidth": 120 },
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "minWidth": 120},
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Emp.ID", "field": "EmployeeID", "minWidth": 120},
			{ "fldType": "TextField", "headerName": "ApplicationFor", "field": "ApplicationFor", "minWidth": 220},
			{ "fldType": "TextField", "headerName": "Status", "field": "Status", "minWidth": 165},            
            { "fldType": "TextField", "headerName": "CustomerID", "field": "CustomerID", "minWidth": 165},
			{ "fldType": "TextField", "headerName": "CustomerType", "field": "CustomerType", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Division", "field": "Division", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Channel", "field": "Channel", "minWidth": 205},
			{ "fldType": "TextField", "headerName": "CreditDays", "field": "CreditDays", "minWidth": 205},
            { "fldType": "TextField", "headerName": "CreditAmount", "field": "CreditAmount", "minWidth": 165},
			{ "fldType": "TextField", "headerName": "BuyerType", "field": "BuyerType", "minWidth": 165},
			{ "fldType": "TextField", "headerName": "NoOfExtProject", "field": "NoOfExtProject", "minWidth": 165},
			{ "fldType": "TextField", "headerName": "NoOfCompletedProject", "field": "NoOfCompletedProject", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Location", "field": "Author.Office", "minWidth": 165, "hide":true},
            { "fldType": "TextField", "headerName": "JobTitle", "field": "Author.JobTitle", "minWidth": 165},
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "minWidth": 165}            
        ]
    }
]
